apiVersion:app/v1
kind: Deployment
metadata:
  name: fox-run-deployment
spec:
  selector:
    matchLabels:
      app:fox-run-app
  replicas: 3
  template:
    metadata:
      labels:
        app:fox-run-app
    spec:
      containers:
      - name: fox-run-container
        image: kg0529/fox-run
        ports:
        - containerPort: 9090
----
apiVersion: v1
kind:Service
metadata:
  name:fox-run-service
spec:
  type: NodePort
  selector:
    app: fox-run-app
    ports:
    - protocl: TCP
      port: 9090
      targetPort: 9090

